# Generated by Django 4.2.30 on 2026-07-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_nurseprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='shift',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
