# Generated by Django 4.2.30 on 2026-07-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_receptionprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('PATIENT', 'Patient'), ('RECEPTION', 'Reception'), ('MANAGER', 'Manager')], default='PATIENT', max_length=20),
        ),
    ]
