# Generated by Django 4.2.30 on 2026-07-01 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='nurseprofile',
            name='shift',
        ),
    ]
