# Generated by Django 4.2.30 on 2026-07-01 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_doctorprofile_shift_remove_nurseprofile_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='nurseprofile',
            name='department',
        ),
    ]
