# Generated by Django 4.2.30 on 2026-07-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_doctorprofile_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='doctor_type',
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='medical_license_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(choices=[('GP', 'General Practitioner'), ('DENTIST', 'Dentist'), ('ORTHOPEDIC', 'Orthopedic'), ('CARDIOLOGY', 'Cardiology'), ('DERMATOLOGY', 'Dermatology'), ('NEUROLOGY', 'Neurology'), ('PEDIATRICS', 'Pediatrics'), ('GYNECOLOGY', 'Gynecology'), ('OPHTHALMOLOGY', 'Ophthalmology'), ('ENT', 'ENT'), ('PSYCHIATRY', 'Psychiatry')], default='bla', max_length=30),
            preserve_default=False,
        ),
    ]
