# Generated by Django 4.2.30 on 2026-07-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='department',
            field=models.CharField(default='Emergency', max_length=100),
            preserve_default=False,
        ),
    ]
