# Generated by Django 4.2.30 on 2026-07-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_shift_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('GP', 'General Practitioner'), ('DENTIST', 'Dentist'), ('ORTHOPEDIC', 'Orthopedic'), ('CARDIOLOGY', 'Cardiology'), ('DERMATOLOGY', 'Dermatology'), ('NEUROLOGY', 'Neurology'), ('PEDIATRICS', 'Pediatrics'), ('GYNECOLOGY', 'Gynecology'), ('OPHTHALMOLOGY', 'Ophthalmology'), ('ENT', 'ENT'), ('PSYCHIATRY', 'Psychiatry')], max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
