# Generated by Django 4.2.30 on 2026-07-01 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_doctorprofile_doctor_type_and_more'),
        ('hospital', '0004_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField()),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('severity', models.CharField(blank=True, choices=[('mild', 'Mild'), ('medium', 'Medium'), ('severe', 'Severe')], max_length=10)),
                ('suggested_specialization', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_checks', to='accounts.patientprofile')),
            ],
        ),
    ]
